name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          
          # On vide la base pour supprimer les infos générales (followers, commits, etc.)
          base: "" 
          
          # Plugin Langages : Tout afficher
          plugin_languages: yes
          plugin_languages_sections: used
          plugin_languages_details: percentage
          plugin_languages_limit: 0
          
          # Plugin Lignes : Pour afficher le total de lignes de code
          plugin_lines: yes
          
          # Configuration de sortie
          output_action: commit
          committer_branch: metrics-render
          committer_message: "chore: update languages and lines metrics"